add_newline = false
format = """
$username\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$fill\
$all\
$line_break\
$character"""

[character]
success_symbol = "[➜](green)"
error_symbol = "[✗](red)"
vimcmd_symbol = "[❮](bold green)"
vimcmd_replace_symbol = "[❮](bold purple)"
vimcmd_visual_symbol = "[❮](bold yellow)"

[fill]
symbol = ' '
