
" Interface settings
set number                    " Show absolute line number on current line
set relativenumber            " Show relative line numbers on other lines
set ruler                     " Show line and column number
set mouse=a                   " Enable mouse support
set showcmd                   " Show command as you type
set showmatch                 " Show matching brackets
set columns=100               " Set the width of the window to 100 columns
set foldcolumn=12             " Add 12 columns of empty space on the left
set numberwidth=8             " Make line number column wider (default is 4)

" Syntax highlighting
syntax on

" Tabs and indentation
set tabstop=4                 " Number of spaces that a <Tab> counts for
set shiftwidth=4              " Number of spaces for autoindent
set expandtab                 " Use spaces instead of tabs
set smartindent               " Automatically indent new lines


" Search settings
set incsearch                 " Enable incremental search
set ignorecase                " Ignore case when searching
set smartcase                 " Override ignorecase if uppercase used
set hlsearch                  " Highlight search matches

" Clipboard
" set clipboard=unnamedplus  " Use system clipboard (Linux X11/Wayland - requires wl-clipboard on Wayland)
set clipboard=unnamed         " Use system clipboard (macOS)

" Performance
set ttyfast                   " Faster scrolling

" File handling
set hidden                    " Allow hidden buffers (switch files without saving)
set noswapfile                " Disable swap files

" Encoding
set encoding=utf-8            " Set encoding

" Key mappings
inoremap jk <Esc>             " Escape insert mode with jk

" Fzf
set rtp+=/opt/homebrew/opt/fzf

" Wrapping settings
set wrap                      " Enable visual wrapping
set linebreak                 " Break at word boundaries
set showbreak=                " No prefix character for wrapped lines
set breakindent               " Preserve indentation when wrapping
