[mgr]
ratio = [1, 3, 4]
sort_by = "natural"
sort_dir_first = true
sort_translit = false
linemode = "mtime"

[preview]
wrap = "yes"
tab_size = 4
image_delay = 100

[plugin]

prepend_previewers = [
  { url = "*.csv", run = "rich-preview" },   # for csv files
  { url = "*.md", run = "rich-preview" },    # for markdown (.md) files
  { url = "*.rst", run = "rich-preview" },   # for restructured text (.rst) files
  { url = "*.ipynb", run = "rich-preview" }, # for jupyter notebooks (.ipynb)
  { url = "*.json", run = "rich-preview" },  # for json (.json) files
  { url = "*.icns", run = "rich-preview" },  # for icns files
  #    { url = "*.lang_type", run = "rich-preview"} # for particular language files eg. .py, .go., .lua, etc.
]

[flavor]
user = "dracula"

[[plugin.prepend_fetchers]]
id    = "git"
url   = "*"
run   = "git"
group = "git"

[[plugin.prepend_fetchers]]
id    = "git"
url   = "*/"
run   = "git"
group = "git"
