# ENABLE VI KEYBINDINGS
set -o vi

# ALIASES
[ -f "$HOME/.config/aliases" ] && source "$HOME/.config/aliases"

# PATH EXPORTS
export PATH="$PATH:/opt/homebrew/bin:$HOME/.local/bin"

# ENABLE STARSHIP PROMPT
export STARSHIP_CONFIG="$HOME/.config/starship/starship.toml"
eval "$(starship init zsh)"

# ENABLE ZOXIDE
eval "$(zoxide init zsh)"

# EXTRAS
#fastfetch
echo $(basename "$STARSHIP_SHELL") | figlet | lolcat --animate --speed 100