" Line numbers
set number                    " Show absolute line number on current line
set relativenumber            " Show relative line numbers on other lines
set numberwidth=8             " Make line number column wider (default is 4)

" UI
set cursorline                " Highlight current line
set showcmd                   " Show command as you type
set showmatch                 " Show matching brackets
set colorcolumn=80            " Highlight column 80
set scroll=10                 " Set scroll to 10 lines
set scrolloff=4               " Keep 4 lines visible above/below cursor

" Syntax highlighting
syntax on

" Mouse
set mouse=a                   " Enable mouse support

" Tabs and indentation
set tabstop=4                 " Number of spaces that a <Tab> counts for
set softtabstop=4             " Number of spaces that a <Tab> counts for in insert mode
set shiftwidth=4              " Number of spaces for autoindent
set expandtab                 " Use spaces instead of tabs

" Search settings
set incsearch                 " Enable incremental search
set ignorecase                " Ignore case when searching
set smartcase                 " Override ignorecase if uppercase used
set hlsearch                  " Highlight search matches

" Clipboard
" set clipboard=unnamedplus  " Use system clipboard (Linux X11/Wayland - requires wl-clipboard on Wayland)
set clipboard=unnamed         " Use system clipboard (macOS)

" Performance
set ttyfast                   " Faster scrolling

" File handling
set hidden                    " Allow hidden buffers (switch files without saving)
set noswapfile                " Disable swap files
set undodir=$HOME/.local/state/vim/undo    " XDG-compliant undo directory
set undofile                  " Enable persistent undo across sessions

" Create undo directory if it doesn't exist
if !isdirectory($HOME . '/.local/state/vim/undo')
    call mkdir($HOME . '/.local/state/vim/undo', 'p', 0700)
endif

" Encoding
set encoding=utf-8            " Set encoding

" Wrapping settings
set nowrap                    " Disable line wrapping

" Terminal
set termguicolors             " Enable 24-bit RGB colors

" Leader key
let mapleader = " "           " Set leader key to space

" Key mappings
inoremap jk <Esc>

" Cursor shape in terminal (Ghostty/xterm DECSCUSR)
" - Normal/Visual: solid block
" - Insert: vertical bar (I-beam)
" - Replace: underline
let &t_SI = "\e[6 q"   " Enter Insert: I-beam
let &t_SR = "\e[4 q"   " Enter Replace: underline
let &t_EI = "\e[2 q"   " Exit Insert/Replace: block

" Install vim-plug if not found
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

" Run PlugInstall if there are missing plugins
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  \ | PlugInstall --sync | source $MYVIMRC
  \ | endif

" Plugin manager (vim-plug)
call plug#begin()

Plug 'dracula/vim', { 'as': 'dracula' }
Plug 'christoomey/vim-tmux-navigator'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'tpope/vim-surround'
Plug 'vim-airline/vim-airline'

call plug#end()

" Airline configuration (settings that don't require functions)
let g:airline#extensions#tabline#enabled = 1           " enable airline tabline
let g:airline#extensions#tabline#formatter = 'unique_tail'
let g:airline_section_b = ''                               " remove branch section
let g:airline_section_c = '%f'                             " show only filename
let g:airline_section_x = ''                               " remove filetype
let g:airline_section_y = ''                               " remove file encoding
let g:airline_section_z = '%l:%c'                          " show only line:column
let g:airline#extensions#whitespace#enabled = 0            " disable whitespace detection
let g:airline_powerline_fonts = 1                          " enable powerline fonts for full width
let g:airline_left_sep = ''                                " full width left separator
let g:airline_right_sep = ''                               " full width right separator
let g:airline#extensions#tabline#left_sep = ''             " tabline left separator
let g:airline#extensions#tabline#right_sep = ''            " tabline right separator
let g:airline_skip_empty_sections = 1                      " skip empty sections

" Airline section_a customization (requires function, set after plugins load)
autocmd VimEnter * if exists('*airline#section#create_left') | let g:airline_section_a = airline#section#create_left(['mode', 'paste']) | endif

" Colorscheme (silent to avoid error on first run before plugins install)
silent! colorscheme dracula

" Transparent background overrides (keep after colorscheme)
hi Normal       ctermbg=NONE guibg=NONE
hi NonText      ctermbg=NONE guibg=NONE
hi LineNr       ctermbg=NONE guibg=NONE
hi FoldColumn   ctermbg=NONE guibg=NONE
hi SignColumn   ctermbg=NONE guibg=NONE
hi EndOfBuffer  ctermbg=NONE guibg=NONE
hi NormalFloat  ctermbg=NONE guibg=NONE
hi FloatBorder  ctermbg=NONE guibg=NONE

" Highlight column 80 background (visible with transparent theme)
hi ColorColumn  ctermbg=238  guibg=#44475a
