# Path/Env
eval "$(/opt/homebrew/bin/brew shellenv)"

# Exports
export BASH_SILENCE_DEPRECATION_WARNING=1
export STARSHIP_CONFIG="$HOME/.config/starship/starship.toml"
export EZA_CONFIG_DIR="$HOME/.config/eza"

# Aliases
[ -f "$HOME/.config/aliases" ] && . "$HOME/.config/aliases"

# Disable: Greeting
[ -f "$HOME/.hushlogin" ] || touch "$HOME/.hushlogin"

# Enable: Starship
eval "$(starship init bash)"

# Enable: VI Keybindings
set -o vi

# Enable: Zoxide
eval "$(zoxide init bash)"

# Extras
$HOME/.config/prompt.sh
