# SILENCE MAC BASH PROMPT
export BASH_SILENCE_DEPRECATION_WARNING=1

# ENABLE VI BINDINGS
set -o vi

# DISABLE BASH GREETING
[ -f "$HOME/.hushlogin" ] || touch "$HOME/.hushlogin"

# ALIASES
[ -f "$HOME/.config/aliases" ] && . "$HOME/.config/aliases"

# PATH EXPORTS
eval "$(/opt/homebrew/bin/brew shellenv)"

# ENABLE STARSHIP PROMPT
export STARSHIP_CONFIG="$HOME/.config/starship/starship.toml"
eval "$(starship init bash)"

# ENABLE ZOXIDE
eval "$(zoxide init bash)"

# EXTRAS
#fastfetch
echo $(basename "$STARSHIP_SHELL") | figlet | lolcat --animate --speed 100
