add_newline = false

[line_break]
disabled = true

[character]
success_symbol = "[➜](green)"
error_symbol = "[✗](red)"
vimcmd_symbol = "[❮](bold green)"
vimcmd_replace_symbol = "[❮](bold purple)"
vimcmd_visual_symbol = "[❮](bold yellow)"
